name: 'Update Helm repo'
description: 'Generates Helm artifacts, merges repo index.yaml with new artifacts and pushes it'
inputs:
  chart_path:
    required: true
    description: 'Path where the Helm chart resides'
  s3_arn:
    required: true
    description: 'ARN for the S3 bucket that stores the helm repository artifacts and manifest'
  repo_url:
    required: true
    description: "Helm repository URL"
  role_arn:
    required: true
    description: 'IAM role for pushing to S3'
  aws_region:
    required: true
    description: 'AWS region used when assuming the IAM role'
runs:
  using: "composite"
  steps:
    - uses: azure/setup-helm@v4.3.1
      with:
        version: 'latest'
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.role_arn }}
        role-session-name: gh-helm-repo-update
        aws-region: ${{ inputs.aws_region }}
    - shell: bash
      name: "Generate helm repo index.yaml"
      env:
        REPO_URL: ${{ inputs.repo_url }}
        CHART_PATH: ${{ inputs.chart_path }}
        S3_ARN: ${{ inputs.s3_arn }}
      run: |
        cd $CHART_PATH
        aws s3 cp s3://$S3_ARN/index.yaml index.yaml
        helm package .
        helm repo index --merge index.yaml --url $REPO_URL .
        cat index.yaml
        aws s3 cp index.yaml s3://$S3_ARN/index.yaml