name: Slack Notifier
description: Alerts to a slack channel

input:
  slack_webhook:
    description: 'Slack webhook'
    required: true
  slack_title:
    description: 'Slack title'
    required: false
  slack_message:
    description: 'Slack message'
    required: true
  slack_icon:
    description: 'Slack icon'
    required: false
    default: 'https://avatars.slack-edge.com/2023-09-22/5958091429776_0ed632ae5f2977693c7d_96.png'
  slack_username:
    description: 'Slack username'
    required: false
    default: 'GitHub Action Notification'
  slack_color:
    description: 'Slack color'
    required: false
    default: 'bad'

runs:
  using: "composite"
  steps:
    - name: Run
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_TITLE: ${{ inputs.slack_title }}
        SLACK_MESSAGE: ${{ inputs.slack_message }}
        SLACK_ICON: ${{ inputs.slack_icon }}
        SLACK_USERNAME: ${{ inputs.slack_username }}
        SLACK_COLOR: ${{ inputs.slack_color }}