name: Slack Notifier
description: Alerts to a slack channel

input:
  slack_webhook:
    description: 'Slack webhook'
    required: true
  slack_channel:
    description: 'Slack channel'
    required: false
  slack_title:
    description: 'Slack title'
    required: false
  slack_message:
    description: 'Slack message'
    required: true
  slack_icon:
    description: 'Slack icon'
    required: false
    default: 'https://avatars.slack-edge.com/2023-09-22/5958091429776_0ed632ae5f2977693c7d_96.png'
  slack_username:
    description: 'Slack username'
    required: false
    default: 'GitHub Action Notification'
  slack_color:
    description: 'Slack color'
    required: false
    default: '#36a64f'

runs:
  using: "composite"
  steps:
    - name: Run
      shell: bash
      run: echo "${{ inputs.slack_message }}"