name: Slack Notifier
description: Alerts to a slack channel
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0
        repository: 'dfds/shared-workflows'
        ref: 'feat/slack-notifications'
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      shell: bash
      run: go build -v .github/actions/automation-slack-notifier/main.go
