name: 'Run Checkov'
description: 'Check policies against Terraform plan file'
inputs:
  tf-policy-repo-token: # id of input
    description: 'Token for TF policy repo'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check tfplan json file
      shell: bash
      run: |
        jsonfile=$RUNNER_TEMP/tfplan.json
        if [ ! -f $jsonfile ]; then
          echo "file does not exist"
          exit 1
        fi
        echo "tfplan.json exits."
        cat $jsonfile | jq '.' > $RUNNER_TEMP/out.json

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Run test checkov
      shell: bash
      env:
        TF_POLICY_REPO_TOKEN: ${{ inputs.tf-policy-repo-token }}
      run: |
        # checkov -f out.json --external-checks-git https://$TF_POLICY_REPO_TOKEN@github.com/dfds/iac-terraform-policies.git//checkov --skip-check '*_AWS_*'
        docker run --rm -v $RUNNER_TEMP/:/files bridgecrew/checkov -f=/files/$RUNNER_TEMP/out.json --external-checks-git https://$TF_POLICY_REPO_TOKEN@github.com/dfds/iac-terraform-policies.git//checkov --skip-check '*_AWS_*'