name: Run tfsec on pull requests

on:
  workflow_call:

jobs:
  TFSec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
