name: Golang test suite
description: Status check that fails if a PR with Golang code fails its test suite.

on:
  pull_request:
    branches: [ master, main ]
    paths:
      - [ '**.go', '**.mod', '**.sum' ]

jobs:
  shared:
    uses: dfds/shared-workflows/.github/workflows/automation-golang-test-suite.yml@master
