name: Build lambda and upload to S3
description: This workflow builds lambda code and uploads the zip file to S3 bucket. The instructions for building the zip package need to be specified in a Makefile. The workflow works with Go and Python lambdas.

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-upload-to-s3:
    name: build-and-upload-to-s3
    uses: dfds/shared-workflows/.github/workflows/automation-build-and-upload-to-s3.yml@master
    with:
      role-session-name: upload-crl-importer-lambda #Session name
      working-directory: ./crl-importer-lambda #The working directory that includes the Makefile
      lambda-package-name: crl-importer-lambda.zip #The lambda package name
      s3-location: dfds-ce-shared-artifacts/iam-rolesanywhere-lambdas
      go-version: "1.20" #Should be specified only for Go lambdas
      cache-dependency-path: ./crl-importer-lambda/go.mod/go.sum #Should be specified only for Go lambdas
      arguments: PACKAGE_NAME=${{ matrix.lambda-name }} #The arguments to be passed to make
    secrets:
      role-to-assume: ${{ secrets.ROLE_TO_ASSUME }} #Repository secret with the AWS role to be assumed
