name: Dispatch to another repo

on:
  workflow_call:
    inputs:
      target-repository:
        required: true
        type: string
      data:
        required: true
        type: string
    secrets:
      workflow-dispatch-auth-token:
        required: true


jobs:
  dispatch-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch-to-${{ inputs.target-repository }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.workflow-dispatch-auth-token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/dfds/${{ inputs.target-repository }}/dispatches \
          -d ${{ inputs.data }}
