
name: Generate Merge Log and Open Pull Request

on:
  workflow_call:
    inputs:
      repository-owner:
        description: 'Repository owner'
        required: true
        type: string
      repository-name:
        description: 'Repository name'
        required: true
        type: string
      main-branch:
        description: 'Main branch name'
        required: true
        type: string
      develop-branch:
        description: 'Develop branch name'
        required: true
        type: string

jobs:
  generate-merge-log-and-open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Merge Log
        run: |
          git fetch --all
          git log --merges --grep='^Merge pull request' --format="- %s%n  Author: %ae%n  Date: %ad" origin/${{ github.event.inputs.main-branch }}..origin/${{ github.event.inputs.develop-branch }} > merge.log

      - name: Extract GitHub Handles
        id: extract-handles
        run: |
          awk -F'<' '{print $2}' merge.log | awk -F'>' '{print $1}' | awk '{print $NF}' > handles.log

      - name: Retrieve Pull Request Titles
        id: fetch-titles
        run: |
          while read -r handle; do
            pr_number="${handle#*#}"
            response=$(curl -s -H "Authorization: Bearer ${{ GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}/pulls/$pr_number")
            title=$(echo "$response" | jq -r '.title')
            echo "$title"
          done < handles.log > titles.log

      - name: Check if Pull Requests Found
        id: check-prs
        run: |
          if [[ ! -s titles.log ]]; then
            echo "No pull requests found in the merge log. Ending the workflow."
            exit 0
          fi

      - name: Retrieve GitHub Names
        id: fetch-names
        run: |
          while read -r handle; do
            response=$(curl -s -H "Authorization: Bearer ${{ GITHUB_TOKEN }}" "https://api.github.com/search/users?q=$handle+in:email")
            name=$(echo "$response" | jq -r '.items[0].login')
            echo "$name"
          done < handles.log > names.log

      - name: Generate Final Merge Log
        id: generate-final-log
        run: |
          paste merge.log names.log titles.log | awk '{print $1,$2,$3,$4,$5,"\n  Author: @"$6,"\n  Date:",$7,$8,"\n  Title:",$9}' > final-merge.log

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ GITHUB_TOKEN }}
          commit-message: Generate Merge Log
          branch: generate-merge-log
          title: Merge Log
          body: |
            ### What has changed
            ```markdown
            $(cat final-merge.log)
            ```

          base: ${{ github.event.inputs.main-branch }}
          repo: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
