
name: Generate Merge Log and Open Pull Request

on:
  workflow_call:
    inputs:
      repository-owner:
        description: 'Repository owner'
        required: true
        type: string
      repository-name:
        description: 'Repository name'
        required: true
        type: string
      main-branch:
        description: 'Main branch name'
        required: true
        type: string
      develop-branch:
        description: 'Develop branch name'
        required: true
        type: string
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  generate-merge-log-and-open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Merge Log
        run: |
          git fetch --all
          git log --no-merges --format="%s%nAuthor: %ae%nDate: %ad%n" origin/${{ inputs.main-branch }}..origin/${{ inputs.develop-branch }} > pr-merge.log
      - name: Merge files
        id: merge-files
        run: |
          echo "### Pull Requests" > body-text.log
          echo "\`\`\`markdown" >> body-text.log
          cat pr-merge.log >> body-text.log
          echo "\`\`\`" >> body-text.log
          echo >> body-text.log
      - name: Create PR
        id: create-pr
        run: |
          gh pr create --title "Automated PR - Merging ${{ inputs.develop-branch }} into ${{ inputs.main-branch }}" -F body-text.log -B ${{ inputs.main-branch }} -H ${{ inputs.develop-branch }}
      - name: Cleanup
        run: |
          git reset --hard
