name: Create repository release

on:
  workflow_call:
    inputs:
      tag_prefix:
        required: false
        type: string
        default: ""
    outputs:
      semver:
        description: "The semantic version of the release"
        value: ${{ jobs.auto-release.outputs.semver }}

jobs:
  auto-release:
    runs-on: ubuntu-latest
    env:
      # If this release should trigger another workflow the `GITHUB_TOKEN`
      # secret must be overriden with the organization secret `GH_RELEASE`:
      # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
      GITHUB_TOKEN: ${{ secrets.GH_RELEASE || secrets.GITHUB_TOKEN }}
    outputs:
      semver: ${{ steps.auto-release-id.outputs.version }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        id: auto-release-id
        with:
          bump_version_scheme: patch
          tag_prefix: ${{ inputs.tag_prefix }}
