name: Generate comment for Renovate PR from template
on:
  workflow_call:
    inputs:
      pr-template-filepath:
        required: true
        type: string

jobs:
  example_comment_pr:
    if: github.triggering_actor == 'devex-sa'
    runs-on: ubuntu-latest
    name: Comment the Pull request
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          file-path: ${{ inputs.pr-template-filepath }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
