name: Build README

on:
  pull_request:
    branches: [ "master", "main" ]
    paths:
      - 'examples/**'
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |-
        python update-readme.py
    - name: Commit and push if changed
      run: |-
        git config --global user.email "readme-bot@dfds.com"
        git config --global user.name "README-bot"
        git add .
        git commit -m "Update readme"
        git push