name: Build README

on:
  pull_request:
    branches: ['master', 'main']
    types: ['opened', 'edited']
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'
      - 'examples/**'
      - 'headline.md'
      - 'update-readme.py'
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    # This makes sure the action only runs on PR's
    # and comments on PR's matching the string
    if: |
      github.event.pull_request ||
      (
        github.event.issue.pull_request &&
        contains(github.event.comment.body, 'build readme')
      )
    steps:
    - name: Check out repo
      uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |
        python update-readme.py
    - name: Commit and push if changed
      run: |
        test -z "$(git status --porcelain)" && exit 0

        git config --global user.email "readme-bot@dfds.com"
        git config --global user.name "README-bot"
        git add .
        git commit -m "Update readme [skip actions]"
        git push