name: Gitleaks

on:
  workflow_call:

jobs:
  Gitleaks:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      -
        name: Scan with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   name: Download Gitleaks
      #   run: |
      #     curl -LO https://github.com/zricethezav/gitleaks/releases/download/v8.15.2/gitleaks_8.15.2_linux_x64.tar.gz
      #     tar zxvf gitleaks_8.15.2_linux_x64.tar.gz
      #     chmod +x gitleaks
      # -
      #   name: Scan with Gitleaks
      #   run: ./gitleaks detect --redact
