name: Testing shared workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: ReadFile
        run: cat read.txt
