name: Housekeeping (Implementation)

on:
  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  shared:
    uses: ./.github/workflows/automation-housekeeping.yml
    secrets: inherit
    with:
      delete_head_branch: true
      squash_merge: true
      branch_protection: true
      status_checks: false
