name: Auto release on merge (Implementation)

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**/*.md"
      - "docs/**"
      - "renovate.json"

jobs:
  auto-release:
      uses: ./.github/workflows/automation-auto-release.yml
