name: Multi architecture docker build

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    inputs:
      image-repo:
        required: true
        type: string
      test-script-path:
        required: false
        type: string
      test-script-cmd:
        required: false
        type: string

jobs:
  multi-build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/amd64,linux/arm/v7,linux/arm64"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ inputs.image-repo }}:test
      - name: Test successful container
        if: "${{ inputs.test-script-path != '' }}"
        run: |
          docker run \
            --rm \
            --volume "$PWD"/${{ inputs.test-script-path }}/:/${{ inputs.test-script-path }} \
            ${{ inputs.image-repo }}:test \
            ${{ inputs.test-script-cmd }}
      - name: Create release
        uses: dfds/shared-workflows/.github/workflows/automation-auto-release.yml@master

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}