name: build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      #- name: Run Trivy vulnerability scanner in IaC mode
      #  uses: aquasecurity/trivy-action@v0.69.2 # This is the version with the fix for the hackerbot-claw incident
      #  with:
      #    scan-type: 'config'
      #    hide-progress: false
      #    format: 'sarif'
      #    output: 'trivy-iac-results.sarif'
      #    exit-code: '0'
      #    ignore-unfixed: true
      #    severity: 'CRITICAL,HIGH'
      #    timeout: '30m'
