name: Run TF plan policy validation

on:
  workflow_call:
    inputs:
      tfplan_json:
        required: true
        type: string
jobs:
  Checkov:
    runs-on: ubuntu-latest
    steps:
      - name: validate
        run: |
          echo ${{ inputs.tfplan_json }}
          # Check the tags value in the TF plan file
          echo "using new repo"
          checkov \
            -f $(Build.BinariesDirectory)/tfplan.json --external-checks-git https://github.com/dfds/iac-terraform-policies.git//checkov  \
            -c TAGGING_POLICY --skip-check '*_AWS_*'