name: Testing

on:
  workflow_call:

jobs:
  Gitleaks:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      -
        name: Test
        run: echo ${GITHUB_REPOSITORY#*/}
