name: Multi architecture docker build

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      SLACK_WEBHOOK:
        required: false
    inputs:
      image-repo:
        required: true
        type: string
      os-archs:
        required: true
        type: string
      test-script-path:
        required: false
        type: string
      test-script-cmd:
        required: false
        type: string
      docker-readme-path:
        required: false
        type: string
      slack-notification:
        required: false
        type: boolean

jobs:
  test-container:
    # Skip this entire test phase if no path is provided
    if: "${{ inputs.test-script-path != '' }}"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ inputs.image-repo }}:test
      - name: Test successful container
        run: |
          docker run \
            --volume "$PWD"/${{ inputs.test-script-path }}/:/${{ inputs.test-script-path }} \
            ${{ inputs.image-repo }}:test \
            ${{ inputs.test-script-cmd }}
