name: Testing

on:
  workflow_call:
    inputs:
      test_var:
        required: true
        type: string

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      -
        name: Test
        run: echo ${{ inputs.test_var }}
